version: '3.13'

services:
  rag-bot:
    build: .
    container_name: psych_rag_bot
    restart: always
    env_file: .env
    volumes:
      - ./faiss_index:/app/faiss_index
      - ./cache:/app/cache
    command: python bot.py
